apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

group = 'com.github.OperatorFoundation'

android {

    namespace 'com.AndFlmsg'

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 33

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }

        externalNativeBuild {
            ndkBuild {
                cFlags "-DHAVE_STRCASESTR"
                cppFlags '-std=c++14'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }

    externalNativeBuild {
        ndkBuild {
            path 'src/main/jni/Android.mk'
        }
    }

    lintOptions {
        checkReleaseBuilds false
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.OperatorFoundation'
                artifactId = 'FldigiAndroid'
            }
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
